//
//  RequestLoginToken.swift
//
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


struct RequestLoginToken {
    var token: String
    var site: String


    init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        token = json["token"] as? String ?? ""
        site = json["site"] as? String ?? ""
    }



    init() {
        self.init(json: [:])!
    }



    init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(token: String, site: String) {
        self.token = token
        self.site = site
    }



    /// This function generate a json dictionary from the model.
    ///
    /// - Parameter useOriginalJsonKey: This parameter take effect only when you have modified a property's name making it different to the original json key. If true, the original json key will be used when generate json dictionary, otherwise, the modified property name will be used as key in the dictionary.
    func jsonDictionary(useOriginalJsonKey: Bool) -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["token"] = token
        dict["site"] = site
        return dict
    }



}



